### ISSUE TITLE
Squashing of PRs

### ISSUE THREAD

**Issue by judovana** [AdoptOpenJDK/IcedTea-Web#164]
Hi!

I would like to introduce policy, which will require squashing where possible, and where have sense.
The non squashed merges, or various "added final keyword"  which usually belongs to single changeset, are makign terrible mess.

If the PR can not be logically squashed, and is ibvuiously msessy, the PR's author should be asked to do visual squash to logical parts.

Thoughts?

**Comment by karianna** [comment]
I'm a fan of the squash merge :-)

**Comment by hendrikebbers** [comment]
I think this can be configured in the GitHub Repo, right?

https://help.github.com/en/articles/configuring-commit-squashing-for-pull-requests

**Comment by judovana** [comment]
Well, yes. But someties it really do nto have sense.

**Comment by sclassen** [comment]
I do not like squashing.
I take careful steps to only include cohesive changes into a single commit. And I hope most of you do the very same.
So squashing the commits will destroy all the discipline which I follow to help me later understand what was changed and for which reason.

I think once the main refactorings are over the commits will not include these massive changes and will be easier to read

**Comment by judovana** [comment]
Actualy most of the main refactorings were exactly the tasks, where many parts should really be squashed, but  really not blindky.

**Comment by sclassen** [comment]
@judovana do you have a general problem with a high number of commits or what is you main intention behind squashing.
From my perspective squashing is always destroying information.

> But once the PR contains eg code formatting as another commit, or some final keywords addition or similarly, then those should be squashed

Do you mean one should squash all formatting commits into a single commit and leaf the commits changing the logic untouched?
Because if you would be proposing to squash the code formatting with the changes of logic into a single commit I would highly disagree. I even ask fellow programmers to split commits if they contain to many refactorings AND logic manipulations. Simply because it becomes very hard to understand the intention in such big commits which are obfuscated by code formatting changes.

TBH I would even propose to reject PR which mix too much of logic and formatting. Then I would ask the author to **first** open a PR with **only formatting** and keywords (i.e. final) and once the code has been tidied up a **second** PR containing the **changes in the logic**.

**Comment by judovana** [comment]
No. for formatting and refactorings MUST be separate PRs!!!! There is noe xcuse on this.

**Comment by judovana** [comment]
What I try to explain is to messing those in single PRs, but validl.
Exampels from recent PRs:
 * New code added ico writer. (commit 1) , but the formatting was wrong, so as commit 2, the formating of NEW code was fixed. Those two really shold be merged.
 * not sue what was the PR,   but there were comits like added final or simialrly.  Those should be squashed, or separate PR whcih would be fixing ALL missing finals.

I'm nott balming the PRs. the ITW was wild thsoe times. But would like to avoid such in future. 


Commit must be logically complete, and final.  PR mus consists  from commits correct commits only, as the  commits are reflected 1:1 into mian tree then.

If commits and PRs do not honor this, the pathces are impossible to backport, and backporting is leading to logical errors.

And againt highlighting, commit is single unifed thing. Any refactoring or formatting (whch is subset of refactoring) must go as seaprate changeset.

I guess I'm not saying anything new to nobody. The good commits are widley described topic, and above are only summary. 

If PR consists only from correct commits, there is of course no squashing in play.

**Comment by judovana** [comment]
@sclassen I think we are speaking about same things. Only I think I'm even more strict then you. Sorry for failing to describe it.
