### ISSUE TITLE
Fatal Launch Error: Could not launch JNLP file. The application has not been initialized

### ISSUE THREAD

**Issue by techRash** [AdoptOpenJDK/IcedTea-Web#512]
When I am trying open jnlp file using javaws32.bat, its giving "Fatal Launch Error: Could not launch JNLP file. The application has not been initialized". Details are as below:

-AdoptOpenJDk version 1.8.0_222 on windows 10
-IceTeaWeb is installed at C:\Program Files\IcedTeaWeb\WebStart\bin
-Path variable -> C:\Program Files (x86)\Java\jdk8u222-b10\bin
-javaws32 version -> icedtea-web 1.7.1

Error logs are attached. Please guide to resolve this issue.

![UnableToOpen](https://user-images.githubusercontent.com/57774775/68898190-93391500-06f4-11ea-9123-17ad760b7d51.png)

[FatalError.log.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3848716/FatalError.log.txt)

**Comment by patris70** [comment]
Hi @techRash,

do you have Proxy or direct Internet connectin?

**Comment by techRash** [comment]
> Hi @techRash,
> 
> do you have Proxy or direct Internet connectin?
> If you do not have Proxy, open **deployment.properties** file and set diese Parameter mit Value ( 0 is for direct connection):
> 
> **deployment.proxy.type=0**

Yes we do have proxy. Please guide what configuration need to be done for proxy.
And this issue ' java.net.SocketException: Connection reset' is not coming while launching all jnlp files on network.

**Comment by patris70** [comment]
Set in deployment.properties file:

deployment.proxy.type=1
deployment.proxy.same=true
deployment.proxy.http.host=Your-Proxy-IP-OR- Name
deployment.proxy.http.port=Your-Proxy-Port
And for example your Proxy Override list are:
deployment.proxy.override.hosts=192.168.1.100,localhost,example.com
deployment.proxy.bypass.list=192.168.1.100,localhost,example.com

More Info:
https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/properties.html

**Comment by karianna** [comment]
Also please use ITW 1.8.x

**Comment by patris70** [comment]
@karianna 
ITW 1.7 or 1.8 does not matter!
His Firefox setting for Proxy uses System Proxy (IE) but ITW kann not uses!
Other way is that he set Proxy manuel in Firefox.
Hope to help

**Comment by Chapma44** [comment]
> Set in deployment.properties file:
> 
> deployment.proxy.type=1
> deployment.proxy.same=true
> deployment.proxy.http.host=Your-Proxy-IP-OR- Name
> deployment.proxy.http.port=Your-Proxy-Port
> 
> Now for example your Proxy Override list are:
> 
> deployment.proxy.override.hosts=192.168.1.100,localhost,example.com
> deployment.proxy.bypass.list=192.168.1.100,localhost,example.com
> 
[fatalErrorPostProxySetup.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3924010/fatalErrorPostProxySetup.txt)

> More Info:
> https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/properties.html

ITW version: 1.8.3

I am assisting with this error as @techRash has other taken to other priorities. I have added the mentioned properties to the deployment.properties file created in the C:/Users/[...]/.config/icedtea-web location. Is that the correct deployment.properties file these values need to be added to. Or do we also have to edit the C:/Sun/java deployment.properties with these values?

Additionally, I have talked to our web server team and found that we only have a HTTPS proxy available. I have added that proxy address to the deployment.properties in the 'deployment.proxy.https.host' value. I have been informed that our HTTPS requires a basic authentication to be passed so that our systems can look up LDAP authorization to that proxy for any user making a request. 

I have included the error log as seen in my command line after running javaws on the JNLP. And just below this I will paste what the configuration of our deployment.properties looks like:

deployment.security.level=ASK_UNSIGNED
deployment.proxy.type=1
deployment.proxy.same=true
deployment.proxy.https.host= **[proxy address]**
deployment.proxy.override.hosts=localhost,.thrivent.com
deployment.proxy.bypass.list=localhost,.thrivent.com
deployment.log=true

Is there any additional solutions you would like us to try that you haven't seen so far?

Thank you for you assistance on this issue. 

[fatalErrorPostProxySetup.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3924014/fatalErrorPostProxySetup.txt)

**Comment by patris70** [comment]
Hi @Chapma44 

Did you create folder C:\Sun\Java yourself?
I asked, because **Oracle Java** create Folder **C:\Windows\Sun\Java\Deployment** as default (this is System-Wide configuration Folder for Java) and **not** C:\Sun\Java
Icedtea-Web uses  this Folder C:\Windows\Sun\Java\Deployment too for System-Wide configuration Folder. If you need using you must create two file in this folder
1- **deployment.config File**
`deployment.system.config=file\:C\:/Windows/Sun/Java/Deployment/deployment.properties
deployment.system.config.mandatory=true`

2- **deployment.properties File**

**Icedtea-Web** uses Folder **C:\Users\\%UserName%\\.config\icedtea-web** folder for User Java configuration parameters (deployment.properties File).

**Oracle Java** uses Folder **C:\Users\\%UserName%\\AppData\LocalLow\sun\java\deployment** for User Java configuration parameters (deployment.properties File).

My suggestion:

Please run **itweb-settings.bat** (this is Icedtea-Web GUI Control Panel) and check your Proxy and other configuration values.

**Comment by Chapma44** [comment]
This ticket can be closed, we did not find a solution, but instead found that the software we were trying to run was very old (java 1.5 / java 1.6). Instead of continuing to push for a solution, we have determined that the owners of that software will need to do an upgrade before we continue trying to find a fix within IcedTeaWeb.

Thanks for your assistance in this troubleshooting.

**Comment by gitrashj** [comment]
Could I please request maintainer to delete my comment which has screenshot as it contains sensitive information. Thank you!

**Comment by sclassen** [comment]
@gitrashj 
I cannot find any comment from you.
According to your github timeline this is the first time since you interacted with the ITW project.

**Comment by techRash** [comment]
@sclassen - Alright I logged in with correct account now. I opened this issue, commented and added a screenshot [on Nov 14, 2019]. Could you please delete it? Thank you!
