### ISSUE TITLE
Cannot access jnlps://<url>

### ISSUE THREAD

**Issue by Rareitor** [AdoptOpenJDK/IcedTea-Web#557]
After installing Openjdk (AdoptOpenJDK JRE 8 232) I can execute jnlp files no problem, but neither Edge, Chrome (79+/-) or Firefox (71+/-)  can invoke javaws or whatever component is supposed to read and parse jnlps:// type urls, at all.
I have not found any way to configure them to do so, and have checked that during the install of OpenJDK I checked all the relevant IcedTea options. 

Relevant address tested:
- jnlps://sp.reniec.gob.pe/app/refirma_suite/pdf/app.jnlp

which is found here:
- https://dsp.reniec.gob.pe/refirma_suite/pdf/web/main.jsf

**Comment by patris70** [comment]
Hi @Rareitor ,

For Firefox:
in about:config add plugin.state.java with Value 1.
OR
Open prefs.js with Editor and add this line:
user_pref("plugin.state.java", 1);

For Chrome or Edge Chromium: 
You must write a Extension (i have no any idea), because Chrome or Edge Chromium  does not launch Java automatically for JNLP resources (Google has configured JNLP file as dangerous with **auto_open_hint: DISALLOW_AUTO_OPEN**).

`https://cs.chromium.org/chromium/src/chrome/browser/resources/safe_browsing/download_file_types.asciipb?type=cs&q=jnlp&g=0&l=755`



regards

**Comment by Rareitor** [comment]
Thank you, I will try this out next week, see if it works.
