### ISSUE TITLE
Getting error while trying to launch using OpenWebStart

### ISSUE THREAD

**Issue by ghost** [AdoptOpenJDK/IcedTea-Web#648]
**Adopt Open JDK** : OpenJDK8U-jre_x64_windows_hotspot_8u232b09

**OpenWebstar**t : v1.1.6

![image](https://user-images.githubusercontent.com/58945429/83148882-16f9a280-a117-11ea-85e3-e96f36ddd56f.png)

Any help/clue?

**Comment by hendrikebbers** [comment]
Hi,
we need some additional information here:
- Have you signed your JARs?
- Have you used custom certificates?

**Comment by sclassen** [comment]
what happens if you click "run"

**Comment by patris70** [comment]
This is NOT error.
This is a Warning because your certificate has expired!

**Comment by NetOps-spectrum** [comment]
Hi Team,

This issue is NOT happening with Oracle JRE, but happening with AdoptOpenJDK while launching/opening JNLP file.
When i click on "Yes" on above warning, it is displaying our login page without any issues.
We did not see any functionality issue, but worrying about Security risk/warning.
  
 We are signing our jars with certificate, which is valid from 12/23/17 8:00 AM to 3/23/29 7:59 AM]
 Please see the our build log
=====================================================
 >>> Signer
    X.509, CN=CA INC, OU=78615, O=CA INC, L=Islandia, ST=New York, C=US
    [trusted certificate]
    X.509, CN=Symantec Class 3 SHA256 Code Signing CA - G2, OU=Symantec Trust Network, O=Symantec Corporation, C=US
    [trusted certificate]
    X.509, CN=VeriSign Universal Root Certification Authority, OU="(c) 2008 VeriSign, Inc. - For authorized use only", OU=VeriSign Trust Network, O="VeriSign, Inc.", C=US
    [trusted certificate]
>>> TSA
    X.509, CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
    [certificate is valid from 12/23/17 8:00 AM to 3/23/29 7:59 AM]
    X.509, CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
    [certificate is valid from 1/12/16 8:00 AM to 1/12/31 7:59 AM]

jar signed.
========================================================

Thanks
Channa

**Comment by patris70** [comment]
Which Oracle Java Version?
Did you delete Oracle Java Cache and startet JNLP?
As Info, Oracle Java give permission using Certificate import.

**Comment by NetOps-spectrum** [comment]
We are using Java Version 1.8(1.8.0_201)
Yes. deleted  Oracle Java Cache and started JNLP, issue not occurring with Oracle JRE

**Comment by patris70** [comment]
Delete all java user certificate store too.
Folder Path is:
c:\users\username\appdata\locallow\Sun\Java\Deployment\Security

**Comment by sclassen** [comment]
@NetOps-spectrum 
In you main jar you should have a MANIFEST.FM file.
Within this file you need to have the following line:
```
Permissions: all-permissions
```
or
```
Permissions: all-permissions
```
The line should match the security property in your JNLP file.

**Comment by NetOps-spectrum** [comment]
i could  not see below path in my environment 
c:\users\username\appdata\locallow\Sun\Java\Deployment\Security

**Comment by NetOps-spectrum** [comment]
In my JNLP file, we have entry "all-permissions" like below
===============================
 <security>
    <all-permissions/>
  </security>
=======================

is this needs to be changed ?

**Comment by NetOps-spectrum** [comment]
In my JNLP file, we have entry "all-permissions" like below
=======================
 <security>
    <all-permissions/>
  </security>
==================
is this needs to be changed ?

**Comment by NetOps-spectrum** [comment]
In my JNLP file, we have entry "all-permissions" like below
=======================
 <security>
    <all-permissions/>
  </security>
==================
is this needs to be changed ?

**Comment by NetOps-spectrum** [comment]
<all-permissions/> under  <security>

**Comment by NetOps-spectrum** [comment]
` <all-permissions/>` under ` <security>`

**Comment by NetOps-spectrum** [comment]
=========================
`<security>
    <all-permissions/>
  </security>`
==========================

**Comment by sclassen** [comment]
No, it just means that you need to have the following line in the MANIFEST.FM of your main jar:
```
Permissions: all-permissions
```

**Comment by sclassen** [comment]
sorry accidentally closed this

**Comment by patris70** [comment]
Open Main JAR File with 7zip, copy here MANIFEST.FM.

**Comment by NetOps-spectrum** [comment]
Hi Team,

I am pasting MANIFEST.MF content here from main jar file
=========================
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.4
Permissions: all-permissions
Codebase: *
Spectrum-Version: 
Created-By: 1.8.0_212-b04 ()

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$1.class
SHA-256-Digest: SaIftccB+MGbExu6/dVMzAfJxUNmUhqOD3dRE/ssECE=

Name: com/aprisma/spectrum/app/console/client/package_ja_JP.properties
SHA-256-Digest: AHVIUFYW4c277jsocOoGf2Jbe5/vo49eXaPVgIHcejU=

Name: com/aprisma/spectrum/app/console/common/ContextDefs.class
SHA-256-Digest: On+WlbowCGHF2ZoYackepw/JOjiSEa/XjHlQva8Oo+Q=

Name: com/aprisma/spectrum/app/console/client/package_zh_TW.properties
SHA-256-Digest: nGOuqlUL79+pu0F9ILqbqj05gxwHc0+FHalkFxUsCoQ=

Name: com/aprisma/spectrum/app/console/client/ConsoleView$TwoPanelNavi
 gationClonedView.class
SHA-256-Digest: FEn+z0oUi+QDbzVMcZB5usk5QYJkmvcSNzxTpDEvm9E=

Name: com/aprisma/spectrum/app/console/client/ConsoleView.class
SHA-256-Digest: S8aho1E2BCjZ2deNH40Wat/d2Uu3DrHmHIpz/PRy0U0=

Name: com/aprisma/spectrum/app/console/client/package_en_US.properties
SHA-256-Digest: jnvHHkhCyHusmcC3aOMnLcLPKIuSfMP7sCihIGDEDTA=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$SwingContextC
 hange.class
SHA-256-Digest: QuaH+Xm/KJL67sF20BAnVmIZUfsdwcEZuyozt1TriBI=

Name: com/aprisma/spectrum/app/console/common/Privileges.class
SHA-256-Digest: Tr3YwipvFO86mTbcDgwFlx6h9MLpX7SSYZnFEntuhz0=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$ClonedViewPre
 f.class
SHA-256-Digest: iTh4WOky3Bq3yynB7czBbrEh3Hk8KRbk+FK01XeTwRY=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$4.class
SHA-256-Digest: 7NVCUp7CwMJNxWeM99KAFSYFhcX48jNd5JiMIMkHdTs=

Name: com/aprisma/spectrum/app/console/client/ConsoleView$TwoPanelNavi
 gationUndockedView.class
SHA-256-Digest: lRlgaFzEmqJtYZ1/fTm+0tqEi1amRU81j3yxvsTR8Lg=

Name: com/aprisma/spectrum/app/console/client/package_zh_CN.properties
SHA-256-Digest: KmcV8Q7YqvnF5f1UjdxTyMDr3cpi1xY03jdlRvHO6XY=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$3.class
SHA-256-Digest: LFTSBGZZxi6+cm20m0mQmYeVw+IxzJbbU8+DTA0TFrU=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp$2.class
SHA-256-Digest: wKFq1odwBUbmq7tD2p6aMekXtK6J1TJpjuWaMyI15So=

Name: com/aprisma/spectrum/app/console/client/ConsoleApp.class
SHA-256-Digest: kqQN9lgDPAqr6WiKv+hBoKaAKd6SMhxh4TPCbx8cBmQ=
==============================================

ican see here parameter "Permissions" set properly as below
======================
Permissions: all-permissions
====================

Thanks
Channa

**Comment by NetOps-spectrum** [comment]
Can we have web-ex, so that i can show issue and "Permissions" settings
Please note that, this is **not** happening for oracle Jre

**Comment by NetOps-spectrum** [comment]
Hi Support Team,

Please let us know your available IST time for web-ex.

Thanks
Channa

**Comment by patris70** [comment]
Wildcard "*" value for Codebase is Problem.
You wrote, user has not java user certificate store (oracle), are you sure???

**Comment by netopyr** [comment]
Hi Channa,

unfortunately we do not offer individual free support. You can find our support options on the OpenWebStart-page: https://openwebstart.com/support/#paid-support-packages.

**Comment by NetOps-spectrum** [comment]
Yes Team,

I don't have folder "Sun\Java\Deployment\Security" under c:\users\username\appdata\locallow\
I have only one folder "Microsoft" under c:\users\username\appdata\locallow\

If wildcard "*" is an issue, but it is working fine with Oracle, in my system has Oracle JRE(1.8.0_201) 

We have official support licence, user name is "NetOps-spectrum"

Thanks
Channa

**Comment by patris70** [comment]
maybe you activated Roaming Profile option under Java Control Panel, check this Folder:
c:\users\username\appdata\roaming\Sun\Java\Deployment\Security
![roaming](https://user-images.githubusercontent.com/39562080/83744190-0d62c400-a65c-11ea-94c8-656b0f257c44.jpg)


Because **Oracle** Java **always** create User Java Folder (in roaming or locallow) for deployment.properties File, Certificate Store, securitypack.jar, exception.seites and etc.

**Comment by NetOps-spectrum** [comment]
![JRE_Options](https://user-images.githubusercontent.com/58945429/83745794-b7057d80-a67b-11ea-80da-34496377b098.jpg)

**Comment by NetOps-spectrum** [comment]
Could you please see my Java settings  above where Oracle JRE is using

**Comment by patris70** [comment]
search this file in C:\ ==> deployment.properties and find folder

How can i check/see/access your Computer?

**Comment by NetOps-spectrum** [comment]
Hi Team,

Below the  deployment.properties content where Oracle JRE exists 
=====================================================
#deployment.properties
#Thu Jun 04 17:46:25 SGT 2020
deployment.expiration.decision.11.201.2=later
deployment.javaws.splash.index=C\:\\Users\\Administrator\\AppData\\LocalLow\\Sun\\Java\\Deployment\\cache\\6.0\\splash\\splash.xml
deployment.version=8
deployment.javaws.appicon.index=C\:\\Users\\Administrator\\AppData\\LocalLow\\Sun\\Java\\Deployment\\cache\\6.0\\appIcon\\appIcon.xml
deployment.browser.path=C\:\\Program Files\\Internet Explorer\\iexplore.exe
deployment.expiration.decision.timestamp.11.201.2=1590579047
deployment.modified.timestamp=1591263985552
deployment.expiration.decision.suppression.11.201.2=false
deployment.roaming.profile=false
#Java Deployment jre's
#Thu Jun 04 17:46:25 SGT 2020
deployment.javaws.jre.1.location=http\://java.sun.com/products/autodl/j2se
deployment.javaws.jre.0.args=
deployment.javaws.jre.0.registered=true
deployment.javaws.jre.1.args=
deployment.javaws.jre.1.enabled=true
deployment.javaws.jre.1.registered=true
deployment.javaws.jre.0.osarch=x86_64
deployment.javaws.jre.0.osname=Windows
deployment.javaws.jre.1.product=1.8.0_201
deployment.javaws.jre.0.platform=1.8
deployment.javaws.jre.0.path=C\:\\Program Files\\Java\\jre1.8.0_201\\bin\\javaw.exe
deployment.javaws.jre.0.location=http\://java.sun.com/products/autodl/j2se
deployment.javaws.jre.1.path=C\:\\Program Files (x86)\\Java\\jre1.8.0_201\\bin\\javaw.exe
deployment.javaws.jre.0.enabled=true
deployment.javaws.jre.1.osarch=x86
deployment.javaws.jre.1.osname=Windows
deployment.javaws.jre.1.platform=1.8
deployment.javaws.jre.0.product=1.8.0_201
===========================================

Please Note:   
- File deployment.properties  is not exists where openJDK is installed
- This issue exits only with  openJDK  but not Oracle JRE
-  Can we have web-ex please, so that we can verify all required settings one time

Thanks
Channa

**Comment by patris70** [comment]
i have not Webex :(

Please delete **Sun** Folder in Path **C:\Users\Administrator\AppData\LocalLow\** and test with Oracle Java again, i am 99% sure, you see Warning with Oracle Java :)

**Comment by sclassen** [comment]
@NetOps-spectrum 
If you already have a support contract, then please contact us on the forum or the mail to setup a call.
We cannot link github accounts to our sponsors

https://board.karakun.com
openwebstart@karakun.com

**Comment by NetOps-spectrum** [comment]
![Sun_Folder_Delete](https://user-images.githubusercontent.com/58945429/83754500-aeb43f00-a689-11ea-9a0d-51be2f5b7275.jpg)

I have renamed Sun folder to Sun_bk, but it got created again when i launch JNLP and i did not get warning/error

**Comment by patris70** [comment]
Have you teamviewer?

**Comment by NetOps-spectrum** [comment]
Not currently, I have Cisco Web-Ex, is this fine ?

**Comment by patris70** [comment]
How can i use Webex?
Need account or can start for free?
If free, can i install.

**Comment by patris70** [comment]
I installed Webex extension in Firefox, how can you share Desktop?

**Comment by sclassen** [comment]
@NetOps-spectrum 
Be advised that patris70 is an active member of the community but not a member of the Karakun support team.
If you have a paid support then please contact the support team by mail or in the forum

**Comment by NetOps-spectrum** [comment]
Thanks for the information. We have the paid support.

**Comment by NetOps-spectrum** [comment]
Hi Support team, 

Any thing you want verify in our environment, I can provide you details/screenshot, our customer is waiting for the solution. Could you please consider this is an high priority. 

Thanks
Channa

**Comment by sclassen** [comment]
@NetOps-spectrum
If you already have a support contract, then please contact us on the forum or the mail to setup a call.
We cannot link github accounts to our sponsors

https://board.karakun.com
openwebstart@karakun.com

**Comment by Cdevon2** [comment]
I also came across this when I first started using OpenWebStart.  I ended up fixing this by adding the `main="true"` attribute to the intended main jar resource.
