### ISSUE TITLE
Problem launching SuperMicro IPMI remote console

### ISSUE THREAD

**Issue by MasterGroosha** [AdoptOpenJDK/IcedTea-Web#669]
Hello, I'm having a strange problem with Supermicro IPMI remote console.
I'm going to some IP addr, for example http://1.2.3.4, which is SuperMicro IPMI Web interface.
Then I go to Remote Console section and launch Remote Console, which loads IcedTea plugin.
However upon launch I'm getting this error:
![изображение](https://user-images.githubusercontent.com/2780044/86392249-ccce8880-bca3-11ea-9a5b-6583f7fbc840.png)

I have literally no idea which certificate is needed and in IcedTea settings page I don't see any SuperMicro-related certificates.

Using Firefox 77.0.1 on Ubuntu 18.04, 
```
> java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```
Installed IcedTea as `apt install -y icedtea-plugin icedtea-netx`

**Comment by sclassen** [comment]
This looks like the CA certificate is not in the trust store.
Can you provide us with log files. It should tell which certificate exactly is missing.

**Comment by MasterGroosha** [comment]
@sclassen the problem is I'm not really sure which certificate I should add to keystore. 

Here are the logs:
1) https://pastebin.com/dgrUqhBh
2) https://pastebin.com/D6iX4g0K
3) https://pastebin.com/E8L4BsR9

**Comment by sclassen** [comment]
While looking at the log files I noticed a stacktrace which contains the following class: `com.ami.kvm.jviewer.JViewer`
This is a class from the client application. Since the client application is only executed once all dependencies are downloaded I suspect that the message you see is not coming from icedtea-web.

A full text search in the code could not find the message from your screenshot.

As a consequence of this you need to contact the author of SuperMicro to find out how to resolve this issue

**Comment by MasterGroosha** [comment]
Thank you very much! Now I see this is not an IcedTea bug.
