### ISSUE TITLE
when using an authenticating proxy, javaws attempts to get the JNLP file before obtaining the credentials from the user

### ISSUE THREAD

**Issue by tnais** [AdoptOpenJDK/IcedTea-Web#699]
I am taking care of an IcedTea based tool that replaces Javas Web Start in a corporate application.
Some of our users work with their machine within customers network where all the outbound http connections passe through an authenticating proxy.

What our use experience is that the proxy credentials dialog box appears and within a second or so, an error dialog box appears declaring that there is an error parsing the JNLP (of course, they got a 403 from the proxy, not a JNLP) and that dialog is modal, preventing the user to fill the fields in the credential form

![image](https://user-images.githubusercontent.com/743875/93340606-50246280-f82d-11ea-8c11-e105ffc3585a.png)

(in the image above, the user can't access the "Authentication Required" dialog since the focus is held by the modal dialog "Error")

We are using icedtea-web 1.8 together with OpenJDK 1.8.0_212-3-redhat

**Comment by hendrikebbers** [comment]
Hi @tnais looks like you are tying to build something like https://github.com/karakun/OpenWebStart ? Are you familiar with OWS? Maybe this already solves your needs.

Otherwise we did a new proxy implementation as part of OWS. You can have a look to the https://github.com/karakun/OpenWebStart repo. I always wanted to downgrade that proxy implementation to IcedTea-Web but found no time until now.

When you want to stay on IcedTea-Web you should maybe switch your dependency to one of the 2.X releases: https://github.com/AdoptOpenJDK/IcedTea-Web/tags

The 2.X releases are used as dependency in OWS, too.

Next to this we are more than happy to receive a PR in any of the mentioned projects :)

**Comment by tnais** [comment]
I packaged an OpenJDK + IcedTea in order to let our users continue to use a Java Web Start application. The "tool" is only that we created a strictly confined deployments in order not to interfere with other OpenJDK 8 or legitimate Oracle Java 1.8 installations the user might have on his/her computer (i.e. people working with SAP). If your advice is to update from IcedTea to OpenWebStart we'll consider the thing.

**Comment by sclassen** [comment]
Checking out OWS is an option. Be advised that it works a little different than ITW.
It does not come with a fixed Java version. Rather it has the capability to download a requested version.
Besides that it works mostly like ITW as it is based on the 2.0.0-alphaX branch of ITW

**Comment by tnais** [comment]
OK, in our tool we pack everithing to make things easiers for the users.

**Comment by Jamila891** [comment]
@tnais How should we proceed with this issue?

**Comment by tnais** [comment]
Hard thing to say... If this could be fixed in IcedTea-Web much better (have I to move the bug notice elsewhere), if it is fixed for sure in OpenWebStart  [say which stable version, the tool is quite important for the company] then put it as solution and we will see what to do on our side.

**Comment by sclassen** [comment]
We currently do not have any proxy with authentication setup.
OWS has re-implemented the entire proxy code. So can you give the version 1.2.1 a shot and report any problems in the OWS issue tracker.
