### ISSUE TITLE
Status of 1.8 and 2.0 versions, roadmap

### ISSUE THREAD

**Issue by SchwingSK** [AdoptOpenJDK/IcedTea-Web#747]
Hi,
as the old mailing list (https://mail.openjdk.java.net/pipermail/distro-pkg-dev/) is dead for IcedTea-Web, I suppose that using GitHub issues is the only way of discussing IcedTea-Web. If there is a better channel for this, please let me know !

I'd like to know the status of the master (which just upgraded from alpha to snasphot state): as of now, AdoptOpenJDK only provides builds for releases of the 1.8 branch; however all releases of OpenWebStart packaged the alpha versions of IcedTea-Web, so it seems to be production ready.

What is preventing a 2.0.0 release ? Is there a public list of regressions/bugs that need to be squashed before the release can happen?
Thanks!

**Comment by sclassen** [comment]
OWS and ITW are currently maintained by the same team of developers. This is also the reason why there are a ton of alpha releases. Because these are then bundled in the OWS release.
The thing is that we do not have enough resources to bring the ITW 2.0.0 into a releasable state.

You are right the code works 99%. But there are some features which are not used in OWS and some features which have a different implementation in OWS. These areas are not tested.
Also the launcher code has not seen much attention and it is likely that it may lacks support for some of the new features.
And finally the entire build is not automated and as you experienced yourself is notoriously difficult to execute.

So the short answer is -> not enough time
The slightly longer is -> we would need to compile a list of tasks to complete (and also tackle them) before it is ready

**Comment by sclassen** [comment]
@SchwingSK is your question answerd?
If so can you please close this issue.

**Comment by SchwingSK** [comment]
@sclassen, yes, sorry for the delay. 
I understand the lack of time (and means). My fear is that given how tedious working on the 1.8 branch is, less and less code will be backported to it, leading to having the maintained version available via OpenWebStart, and the old 1.8 branch being distributed by AdoptOpenJDK & Azul.
However things are improving, notably by the current work on github actions to build 1.8 & master, that gives an hint on how to build ITW.
